version: "3"

services:
  mongodb-mpgu:
    container_name: mongodb-mpgu
    image: mongo:4.4.6
    volumes:
      - ./mongodb-master-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - integrationbot
    logging:
        driver: "json-file"
        options:
            max-size: "2048m"


  integration:
    container_name: integration
    build: ./
    command: poetry run python main.py
    depends_on:
      - mongodb-mpgu
    networks:
      - integrationbot
    logging:
        driver: "json-file"
        options:
            max-size: "2048m"

  applicants-bot:
    container_name: applicants-bot
    build: ./
    command: poetry run python bot.py
    depends_on:
      - mongodb-mpgu
    networks:
      - integrationbot
    logging:
        driver: "json-file"
        options:
            max-size: "2048m"

networks:
  integrationbot:
    external: true
