version: "3"

services:
  mongodb-mpgu:
    container_name: mongodb-mpgu
    image: mongo
    volumes:
      - ./mongodb-master-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - integrationbot


  integration:
    container_name: integration
    build: ./
    command: poetry run python main.py
    depends_on:
      - mongodb-mpgu
    networks:
      - integrationbot

  applicants-bot:
    container_name: applicants-bot
    build: ./
    command: poetry run python bot.py
    depends_on:
      - mongodb-mpgu
    networks:
      - integrationbot

networks:
  integrationbot:
    external: true
